export const resumeTemplates = [
  {
    id: 1,
    name: "Classic Professional",
    category: "Professional",
    style: "Classic",
    description: "Traditional layout perfect for corporate roles",
    primaryColor: "#2c3e50",
    secondaryColor: "#34495e",
    previewBg: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)",
    layout: "single-column",
    fontFamily: "'Times New Roman', serif",
  },
  {
    id: 2,
    name: "Modern Minimal",
    category: "Fresher",
    style: "Modern",
    description: "Clean and contemporary design for fresh graduates",
    primaryColor: "#3498db",
    secondaryColor: "#2980b9",
    previewBg: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    layout: "two-column",
    fontFamily: "'Arial', sans-serif",
  },
  {
    id: 3,
    name: "Bold Executive",
    category: "Experienced",
    style: "Professional",
    description: "Strong presence for senior positions",
    primaryColor: "#e74c3c",
    secondaryColor: "#c0392b",
    previewBg: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    layout: "single-column",
    fontFamily: "'Georgia', serif",
  },
  {
    id: 4,
    name: "Creative Edge",
    category: "Professional",
    style: "Creative",
    description: "Stand out in creative industries",
    primaryColor: "#9b59b6",
    secondaryColor: "#8e44ad",
    previewBg: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    layout: "two-column",
    fontFamily: "'Verdana', sans-serif",
  },
  {
    id: 5,
    name: "Elegant Scholar",
    category: "Student",
    style: "Classic",
    description: "Perfect for academic and research positions",
    primaryColor: "#16a085",
    secondaryColor: "#1abc9c",
    previewBg: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    layout: "single-column",
    fontFamily: "'Palatino', serif",
  },
  {
    id: 6,
    name: "Tech Innovator",
    category: "Professional",
    style: "Modern",
    description: "Designed for tech and IT professionals",
    primaryColor: "#27ae60",
    secondaryColor: "#229954",
    previewBg: "linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)",
    layout: "two-column",
    fontFamily: "'Courier New', monospace",
  },
  {
    id: 7,
    name: "Clean Slate",
    category: "Fresher",
    style: "Minimalist",
    description: "Minimalist design that lets your experience shine",
    primaryColor: "#34495e",
    secondaryColor: "#2c3e50",
    previewBg: "linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)",
    layout: "single-column",
    fontFamily: "'Calibri', sans-serif",
  },
  {
    id: 8,
    name: "Dynamic Edge",
    category: "Experienced",
    style: "Modern",
    description: "Modern layout for experienced professionals",
    primaryColor: "#e67e22",
    secondaryColor: "#d35400",
    previewBg: "linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)",
    layout: "two-column",
    fontFamily: "'Arial', sans-serif",
  },
  {
    id: 9,
    name: "Contemporary Pro",
    category: "Professional",
    style: "Professional",
    description: "Balanced design for various industries",
    primaryColor: "#2980b9",
    secondaryColor: "#3498db",
    previewBg: "linear-gradient(135deg, #fad0c4 0%, #ffd1ff 100%)",
    layout: "single-column",
    fontFamily: "'Helvetica', sans-serif",
  },
  {
    id: 10,
    name: "Student Focus",
    category: "Student",
    style: "Minimalist",
    description: "Simple and effective for student applications",
    primaryColor: "#f39c12",
    secondaryColor: "#f1c40f",
    previewBg: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)",
    layout: "two-column",
    fontFamily: "'Arial', sans-serif",
  },
]

export const defaultResumeData = {
  personalInfo: {
    fullName: "Your Full Name",
    email: "your.email@example.com",
    phone: "+1 (555) 123-4567",
    location: "City, State",
    linkedin: "linkedin.com/in/yourprofile",
    portfolio: "yourportfolio.com",
  },
  summary:
    "Dedicated professional with a proven track record of success. Seeking opportunities to leverage skills and experience to contribute to organizational growth.",
  experience: [
    {
      id: 1,
      title: "Job Title",
      company: "Company Name",
      location: "City, State",
      startDate: "Jan 2022",
      endDate: "Present",
      description:
        "Led key initiatives resulting in measurable improvements. Collaborated with cross-functional teams to deliver projects on time.",
    },
  ],
  education: [
    {
      id: 1,
      degree: "Bachelor of Science",
      institution: "University Name",
      location: "City, State",
      graduationDate: "May 2021",
      gpa: "3.8/4.0",
    },
  ],
  skills: [
    "Project Management",
    "Communication",
    "Problem Solving",
    "Leadership",
    "Data Analysis",
    "Microsoft Office",
    "Team Collaboration",
    "Time Management",
  ],
  certifications: [
    {
      id: 1,
      name: "Professional Certification",
      issuer: "Issuing Organization",
      date: "2023",
    },
  ],
}
